# Global settings shared by all environments
[env]
framework = arduino
monitor_speed = 115200

# Environment for the Arduino Uno
[env:uno]
platform = atmelavr
board = uno
framework = arduino
# Declare external libraries here (Name or ID from registry, or Git URL)
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.0
    milesburton/DallasTemperature @ ^3.9.1

# Environment for an ESP32 board
[env:esp32dev]
platform = espressif32
board = esp32dev

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200

# Add these build flags to satisfy the Heltec LoRa library requirements
build_flags =
    -D REGION_US915
    -D ACTIVE_REGION=LORAMAC_REGION_US915
    -D LoRaWAN_DEBUG_LEVEL=0
    -D HELTEC_BOARD=0
    -D SLOW_CLK_TPYE=0

lib_deps =
    heltecautomation/Heltec ESP32 Dev-Boards @ ^2.0.2