# Global settings shared by all environments
[env]
framework = arduino
monitor_speed = 115200

# Environment for the Arduino Uno
[env:uno]
platform = atmelavr
board = uno
framework = arduino
# Declare external libraries here (Name or ID from registry, or Git URL)
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.0
    milesburton/DallasTemperature @ ^3.9.1

# Environment for an ESP32 board
[env:esp32dev]
platform = espressif32
board = esp32dev

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200

# Automatically pull the official Heltec V3 library suite
lib_deps =
    heltecautomation/Heltec ESP32 Dev-Boards @ ^2.0.2